name: get_job_id
description: Easily get the job id of the current job.
author: bwhitehead0
inputs:
outputs:
  job_id:
    description: GitHub Actions Job ID
    value: ${{ steps.get_job_id.outputs.job_id }}
runs:
  using: 'composite'
  steps:
    - name: Get Job ID
      id: get_job_id
      run: ${{ github.action_path }}/assets/get_job_id.sh
      shell: bash

branding:
  icon: 'info'
  color: 'green'